[package]
name = "adi2edi"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.16", features = ["derive"] }
pest = "2.7.5"
pest_derive = "2.7.5"
strip_bom = "1.0.0"
